### PR TITLE
adding xxxxs

### PR DESCRIPTION
**Pull request by skariel**

### CODE REVIEW

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
@skariel|0.00
@theindiepocalypse|5.00
@crazyduck2|95.00
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: no requested percentage for merging yet
thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse request 3.4%

**Comment by theindiepocalypse** [comment]
@skariel: request for merge created as 3.4%%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3.4%
required for acceptance: not even for free ;)
is negotiation succesful? not yet

**Comment by crazyduck2** [comment]
@theindiepocalypse offer 3.4%

**Comment by theindiepocalypse** [comment]
@crazyduck2: offer for merge created as 3.4%
nego status:

ownership currently accepted: 95.00%
users currently accepted: @crazyduck2
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3.40%
required for acceptance: 3.40%
is negotiation succesful? yes!

negotiation succesful. Merging

merged!
The new ownership structure:



Owner | Percent
-------|---------
@skariel|3.23
@theindiepocalypse|4.83
@crazyduck2|91.77
*total* | 100.0

**Pull request merged**
